"""persist bulk stock counts

Revision ID: 1e499af22243
Revises: f4b2ace7cb36
Create Date: 2026-07-03 01:09:54.848306
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "1e499af22243"
down_revision: Union[str, None] = "f4b2ace7cb36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected','obsolete')",
            name=op.f("ck_stock_imports_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_stock_imports_decided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_stock_imports_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_imports_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_imports")),
    )
    op.create_index(
        op.f("ix_stock_imports_requested_by_user_id"),
        "stock_imports",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_imports_status"), "stock_imports", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_stock_imports_warehouse_id"),
        "stock_imports",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "stock_import_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("stock_import_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("previous_physical_confirmed", sa.BigInteger(), nullable=False),
        sa.Column("counted_physical_confirmed", sa.BigInteger(), nullable=False),
        sa.Column("position_version", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "previous_physical_confirmed >= 0",
            name=op.f("ck_stock_import_lines_previous_nonnegative"),
        ),
        sa.CheckConstraint(
            "counted_physical_confirmed >= 0",
            name=op.f("ck_stock_import_lines_counted_nonnegative"),
        ),
        sa.CheckConstraint(
            "position_version > 0", name=op.f("ck_stock_import_lines_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_import_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["stock_import_id"],
            ["stock_imports.id"],
            name=op.f("fk_stock_import_lines_stock_import_id_stock_imports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_import_lines")),
        sa.UniqueConstraint(
            "stock_import_id", "product_id", name="uq_stock_import_product"
        ),
    )
    op.create_index(
        op.f("ix_stock_import_lines_stock_import_id"),
        "stock_import_lines",
        ["stock_import_id"],
        unique=False,
    )
    for table_name in ("stock_imports", "stock_import_lines"):
        op.execute(
            sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
        )
        op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
        op.execute(
            sa.text(f"""DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN REVOKE ALL ON TABLE public."{table_name}" FROM anon; END IF;
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN REVOKE ALL ON TABLE public."{table_name}" FROM authenticated; END IF;
        END $$""")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_import_lines_stock_import_id"), table_name="stock_import_lines"
    )
    op.drop_table("stock_import_lines")
    op.drop_index(op.f("ix_stock_imports_warehouse_id"), table_name="stock_imports")
    op.drop_index(op.f("ix_stock_imports_status"), table_name="stock_imports")
    op.drop_index(
        op.f("ix_stock_imports_requested_by_user_id"), table_name="stock_imports"
    )
    op.drop_table("stock_imports")
    # ### end Alembic commands ###
