"""create dispatches and incidents

Revision ID: 424d11eb28cf
Revises: f0e10820378c
Create Date: 2026-07-06 20:11:19.194872
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "424d11eb28cf"
down_revision: Union[str, None] = "f0e10820378c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dispatches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responsible_name", sa.String(length=160), nullable=False),
        sa.Column("recipient", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("confirmed_by_user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_id"],
            ["users.id"],
            name=op.f("fk_dispatches_confirmed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_dispatches_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatches")),
    )
    op.create_index(
        op.f("ix_dispatches_dispatched_at"),
        "dispatches",
        ["dispatched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispatches_invoice_id"), "dispatches", ["invoice_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("incident_type", sa.String(length=60), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=True),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("affected_quantity", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("responsible_name", sa.String(length=160), nullable=True),
        sa.Column("decision", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('open','in_review','resolved','closed')",
            name=op.f("ck_incidents_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_incidents_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_incidents_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_incidents_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_incidents_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incidents")),
    )
    op.create_index(
        op.f("ix_incidents_incident_type"), "incidents", ["incident_type"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_invoice_id"), "incidents", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_incidents_product_id"), "incidents", ["product_id"], unique=False
    )
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "dispatch_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("dispatch_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_line_id", sa.Uuid(), nullable=False),
        sa.Column("dispatched_quantity", sa.BigInteger(), nullable=False),
        sa.Column("missing_quantity", sa.BigInteger(), nullable=False),
        sa.Column("missing_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "dispatched_quantity + missing_quantity > 0",
            name=op.f("ck_dispatch_lines_reported_positive"),
        ),
        sa.CheckConstraint(
            "dispatched_quantity >= 0",
            name=op.f("ck_dispatch_lines_dispatched_nonnegative"),
        ),
        sa.CheckConstraint(
            "missing_quantity >= 0", name=op.f("ck_dispatch_lines_missing_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["dispatch_id"],
            ["dispatches.id"],
            name=op.f("fk_dispatch_lines_dispatch_id_dispatches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["invoice_line_id"],
            ["invoice_lines.id"],
            name=op.f("fk_dispatch_lines_invoice_line_id_invoice_lines"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dispatch_lines")),
    )
    op.create_index(
        op.f("ix_dispatch_lines_dispatch_id"),
        "dispatch_lines",
        ["dispatch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dispatch_lines_invoice_line_id"),
        "dispatch_lines",
        ["invoice_line_id"],
        unique=False,
    )
    for table_name in ("dispatches", "dispatch_lines", "incidents"):
        op.execute(
            sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
        )
        op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
        op.execute(
            sa.text(f"""DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE public."{table_name}" FROM anon; END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE public."{table_name}" FROM authenticated; END IF;
        END $$""")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dispatch_lines_invoice_line_id"), table_name="dispatch_lines"
    )
    op.drop_index(op.f("ix_dispatch_lines_dispatch_id"), table_name="dispatch_lines")
    op.drop_table("dispatch_lines")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_product_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_invoice_id"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_incident_type"), table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_dispatches_invoice_id"), table_name="dispatches")
    op.drop_index(op.f("ix_dispatches_dispatched_at"), table_name="dispatches")
    op.drop_table("dispatches")
    # ### end Alembic commands ###
