"""create returns and invoice adjustments

Revision ID: 8110e6de503e
Revises: d30ebc85b825
Create Date: 2026-07-06 20:24:17.577592
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "8110e6de503e"
down_revision: Union[str, None] = "d30ebc85b825"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoice_adjustments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=20), nullable=False),
        sa.Column("document_number", sa.String(length=80), nullable=False),
        sa.Column("document_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("registered_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "document_type IN ('credit_note','debit_note')",
            name=op.f("ck_invoice_adjustments_valid_type"),
        ),
        sa.CheckConstraint(
            "value >= 0", name=op.f("ck_invoice_adjustments_value_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_adjustments_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_user_id"],
            ["users.id"],
            name=op.f("fk_invoice_adjustments_registered_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_adjustments")),
        sa.UniqueConstraint(
            "document_type", "document_number", name="uq_adjustment_type_number"
        ),
    )
    op.create_index(
        op.f("ix_invoice_adjustments_invoice_id"),
        "invoice_adjustments",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "returns",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("registered_by_user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_returns_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_user_id"],
            ["users.id"],
            name=op.f("fk_returns_registered_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_returns")),
    )
    op.create_index(
        op.f("ix_returns_invoice_id"), "returns", ["invoice_id"], unique=False
    )
    op.create_index(
        op.f("ix_returns_returned_at"), "returns", ["returned_at"], unique=False
    )
    op.create_table(
        "return_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("return_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_line_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("disposition", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "disposition IN ('available_warehouse','available_floor','blocked','damaged','in_review','unusable')",
            name=op.f("ck_return_lines_valid_disposition"),
        ),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_return_lines_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_line_id"],
            ["invoice_lines.id"],
            name=op.f("fk_return_lines_invoice_line_id_invoice_lines"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["return_id"],
            ["returns.id"],
            name=op.f("fk_return_lines_return_id_returns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_return_lines")),
    )
    op.create_index(
        op.f("ix_return_lines_invoice_line_id"),
        "return_lines",
        ["invoice_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_return_lines_return_id"), "return_lines", ["return_id"], unique=False
    )
    for table_name in ("invoice_adjustments", "returns", "return_lines"):
        op.execute(
            sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
        )
        op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
        op.execute(
            sa.text(f"""DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE public."{table_name}" FROM anon; END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE public."{table_name}" FROM authenticated; END IF;
        END $$""")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_return_lines_return_id"), table_name="return_lines")
    op.drop_index(op.f("ix_return_lines_invoice_line_id"), table_name="return_lines")
    op.drop_table("return_lines")
    op.drop_index(op.f("ix_returns_returned_at"), table_name="returns")
    op.drop_index(op.f("ix_returns_invoice_id"), table_name="returns")
    op.drop_table("returns")
    op.drop_index(
        op.f("ix_invoice_adjustments_invoice_id"), table_name="invoice_adjustments"
    )
    op.drop_table("invoice_adjustments")
    # ### end Alembic commands ###
