"""create catalog and inventory

Revision ID: b4e9205ab100
Revises: 20260703_0001
Create Date: 2026-07-03 00:49:25.872172
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "b4e9205ab100"
down_revision: str | None = "20260703_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def enable_rls(table_name: str) -> None:
    op.execute(sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY'))
    op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
    op.execute(
        sa.text(
            f"""
            DO $$
            BEGIN
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
                    REVOKE ALL ON TABLE public."{table_name}" FROM anon;
                END IF;
                IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
                    REVOKE ALL ON TABLE public."{table_name}" FROM authenticated;
                END IF;
            END
            $$
            """
        )
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("barcode", sa.String(length=80), nullable=True),
        sa.Column("contifico_aux_code", sa.String(length=80), nullable=True),
        sa.Column("cost", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("units_per_box", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("cost >= 0", name=op.f("ck_products_cost_nonnegative")),
        sa.CheckConstraint(
            "units_per_box > 0", name=op.f("ck_products_units_per_box_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
    )
    op.create_index(op.f("ix_products_barcode"), "products", ["barcode"], unique=False)
    op.create_index(
        op.f("ix_products_category"), "products", ["category"], unique=False
    )
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_table(
        "warehouses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("code", name=op.f("uq_warehouses_code")),
    )
    op.create_table(
        "inventory_positions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("physical_confirmed", sa.BigInteger(), nullable=False),
        sa.Column("reserved", sa.BigInteger(), nullable=False),
        sa.Column("invoiced_not_dispatched", sa.BigInteger(), nullable=False),
        sa.Column("blocked_by_incident", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "blocked_by_incident >= 0",
            name=op.f("ck_inventory_positions_blocked_nonnegative"),
        ),
        sa.CheckConstraint(
            "invoiced_not_dispatched >= 0",
            name=op.f("ck_inventory_positions_invoiced_pending_nonnegative"),
        ),
        sa.CheckConstraint(
            "physical_confirmed >= 0",
            name=op.f("ck_inventory_positions_physical_nonnegative"),
        ),
        sa.CheckConstraint(
            "reserved >= 0", name=op.f("ck_inventory_positions_reserved_nonnegative")
        ),
        sa.CheckConstraint(
            "version > 0", name=op.f("ck_inventory_positions_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_positions_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_positions_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_positions")),
        sa.UniqueConstraint(
            "warehouse_id", "product_id", name="uq_position_warehouse_product"
        ),
    )
    op.create_index(
        op.f("ix_inventory_positions_product_id"),
        "inventory_positions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_positions_warehouse_id"),
        "inventory_positions",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "inventory_movements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("movement_type", sa.String(length=60), nullable=False),
        sa.Column("reference_type", sa.String(length=60), nullable=True),
        sa.Column("reference_id", sa.String(length=100), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "before_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column(
            "after_value",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_movements_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_inventory_movements_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_movements_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_movements")),
    )
    op.create_index(
        op.f("ix_inventory_movements_actor_user_id"),
        "inventory_movements",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_movement_type"),
        "inventory_movements",
        ["movement_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_occurred_at"),
        "inventory_movements",
        ["occurred_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_product_id"),
        "inventory_movements",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_movements_warehouse_id"),
        "inventory_movements",
        ["warehouse_id"],
        unique=False,
    )
    op.drop_constraint(op.f("fk_users_role_id_roles"), "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_users_role_id_roles"),
        "users",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.execute(
        sa.text(
            """
            INSERT INTO warehouses (id, code, name, created_at)
            VALUES (
              '00000000-0000-4000-8000-000000000010',
              'principal',
              'Bodega principal',
              CURRENT_TIMESTAMP
            )
            """
        )
    )
    for table_name in (
        "products",
        "warehouses",
        "inventory_positions",
        "inventory_movements",
    ):
        enable_rls(table_name)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_users_role_id_roles"), "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_users_role_id_roles"), "users", "roles", ["role_id"], ["id"]
    )
    op.drop_index(
        op.f("ix_inventory_movements_warehouse_id"), table_name="inventory_movements"
    )
    op.drop_index(
        op.f("ix_inventory_movements_product_id"), table_name="inventory_movements"
    )
    op.drop_index(
        op.f("ix_inventory_movements_occurred_at"), table_name="inventory_movements"
    )
    op.drop_index(
        op.f("ix_inventory_movements_movement_type"), table_name="inventory_movements"
    )
    op.drop_index(
        op.f("ix_inventory_movements_actor_user_id"), table_name="inventory_movements"
    )
    op.drop_table("inventory_movements")
    op.drop_index(
        op.f("ix_inventory_positions_warehouse_id"), table_name="inventory_positions"
    )
    op.drop_index(
        op.f("ix_inventory_positions_product_id"), table_name="inventory_positions"
    )
    op.drop_table("inventory_positions")
    op.drop_table("warehouses")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_category"), table_name="products")
    op.drop_index(op.f("ix_products_barcode"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
