"""create reservations

Revision ID: bf6f2fe37b65
Revises: 1e499af22243
Create Date: 2026-07-03 01:17:08.017508
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "bf6f2fe37b65"
down_revision: Union[str, None] = "1e499af22243"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("closed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("purpose", sa.String(length=30), nullable=False),
        sa.Column("customer_name", sa.String(length=160), nullable=True),
        sa.Column("purchase_order_reference", sa.String(length=100), nullable=True),
        sa.Column("responsible_name", sa.String(length=160), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('customer','purchase_order','seller','pending_order','operational')",
            name=op.f("ck_reservations_valid_purpose"),
        ),
        sa.CheckConstraint(
            "status IN ('active','released','used','cancelled')",
            name=op.f("ck_reservations_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["closed_by_user_id"],
            ["users.id"],
            name=op.f("fk_reservations_closed_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_reservations_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_reservations_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservations")),
    )
    op.create_index(
        op.f("ix_reservations_created_at"), "reservations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_reservations_created_by_user_id"),
        "reservations",
        ["created_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reservations_purchase_order_reference"),
        "reservations",
        ["purchase_order_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reservations_status"), "reservations", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_reservations_warehouse_id"),
        "reservations",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "reservation_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("reservation_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("remaining_quantity", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_reservation_lines_quantity_positive")
        ),
        sa.CheckConstraint(
            "remaining_quantity >= 0 AND remaining_quantity <= quantity",
            name=op.f("ck_reservation_lines_remaining_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_reservation_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["reservations.id"],
            name=op.f("fk_reservation_lines_reservation_id_reservations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reservation_lines")),
        sa.UniqueConstraint(
            "reservation_id", "product_id", name="uq_reservation_product"
        ),
    )
    op.create_index(
        op.f("ix_reservation_lines_product_id"),
        "reservation_lines",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reservation_lines_reservation_id"),
        "reservation_lines",
        ["reservation_id"],
        unique=False,
    )
    for table_name in ("reservations", "reservation_lines"):
        op.execute(
            sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
        )
        op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
        op.execute(
            sa.text(f"""DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE public."{table_name}" FROM anon; END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE public."{table_name}" FROM authenticated; END IF;
        END $$""")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_reservation_lines_reservation_id"), table_name="reservation_lines"
    )
    op.drop_index(
        op.f("ix_reservation_lines_product_id"), table_name="reservation_lines"
    )
    op.drop_table("reservation_lines")
    op.drop_index(op.f("ix_reservations_warehouse_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_status"), table_name="reservations")
    op.drop_index(
        op.f("ix_reservations_purchase_order_reference"), table_name="reservations"
    )
    op.drop_index(op.f("ix_reservations_created_by_user_id"), table_name="reservations")
    op.drop_index(op.f("ix_reservations_created_at"), table_name="reservations")
    op.drop_table("reservations")
    # ### end Alembic commands ###
