"""create purchase orders

Revision ID: d285e7fb0c6c
Revises: bf6f2fe37b65
Create Date: 2026-07-06 20:04:42.564920
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d285e7fb0c6c"
down_revision: Union[str, None] = "bf6f2fe37b65"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "purchase_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("chain_name", sa.String(length=160), nullable=False),
        sa.Column("customer_name", sa.String(length=160), nullable=True),
        sa.Column("order_number", sa.String(length=100), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=True),
        sa.Column("destination", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('open','partially_invoiced','completed','cancelled')",
            name=op.f("ck_purchase_orders_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_purchase_orders_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint(
            "chain_name", "order_number", name="uq_purchase_order_chain_number"
        ),
    )
    op.create_index(
        op.f("ix_purchase_orders_chain_name"),
        "purchase_orders",
        ["chain_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_customer_name"),
        "purchase_orders",
        ["customer_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_order_number"),
        "purchase_orders",
        ["order_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_status"), "purchase_orders", ["status"], unique=False
    )
    op.create_table(
        "purchase_order_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("ordered_quantity", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "ordered_quantity > 0",
            name=op.f("ck_purchase_order_lines_ordered_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_purchase_order_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_purchase_order_lines_purchase_order_id_purchase_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_lines")),
        sa.UniqueConstraint(
            "purchase_order_id", "product_id", name="uq_purchase_order_product"
        ),
    )
    op.create_index(
        op.f("ix_purchase_order_lines_purchase_order_id"),
        "purchase_order_lines",
        ["purchase_order_id"],
        unique=False,
    )
    for table_name in ("purchase_orders", "purchase_order_lines"):
        op.execute(
            sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
        )
        op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
        op.execute(
            sa.text(f"""DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE public."{table_name}" FROM anon; END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE public."{table_name}" FROM authenticated; END IF;
        END $$""")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_purchase_order_lines_purchase_order_id"),
        table_name="purchase_order_lines",
    )
    op.drop_table("purchase_order_lines")
    op.drop_index(op.f("ix_purchase_orders_status"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_order_number"), table_name="purchase_orders")
    op.drop_index(
        op.f("ix_purchase_orders_customer_name"), table_name="purchase_orders"
    )
    op.drop_index(op.f("ix_purchase_orders_chain_name"), table_name="purchase_orders")
    op.drop_table("purchase_orders")
    # ### end Alembic commands ###
