"""create deliveries

Revision ID: d30ebc85b825
Revises: 424d11eb28cf
Create Date: 2026-07-06 20:14:00.792850
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "d30ebc85b825"
down_revision: Union[str, None] = "424d11eb28cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("delivery_type", sa.String(length=30), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recipient", sa.String(length=160), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("registered_by_user_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "delivery_type IN ('without_issue','confirmed','with_issue')",
            name=op.f("ck_deliveries_valid_type"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_deliveries_invoice_id_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["registered_by_user_id"],
            ["users.id"],
            name=op.f("fk_deliveries_registered_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deliveries")),
    )
    op.create_index(
        op.f("ix_deliveries_delivered_at"), "deliveries", ["delivered_at"], unique=False
    )
    op.create_index(
        op.f("ix_deliveries_invoice_id"), "deliveries", ["invoice_id"], unique=False
    )
    op.execute(sa.text('ALTER TABLE public."deliveries" ENABLE ROW LEVEL SECURITY'))
    op.execute(sa.text('REVOKE ALL ON TABLE public."deliveries" FROM PUBLIC'))
    op.execute(
        sa.text("""DO $$ BEGIN
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE public.deliveries FROM anon; END IF;
      IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE public.deliveries FROM authenticated; END IF;
    END $$""")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_deliveries_invoice_id"), table_name="deliveries")
    op.drop_index(op.f("ix_deliveries_delivered_at"), table_name="deliveries")
    op.drop_table("deliveries")
    # ### end Alembic commands ###
