"""create external invoices

Revision ID: f0e10820378c
Revises: d285e7fb0c6c
Create Date: 2026-07-06 20:08:11.801336
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "f0e10820378c"
down_revision: Union[str, None] = "d285e7fb0c6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_number", sa.String(length=17), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("purchase_order_id", sa.Uuid(), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("customer_name", sa.String(length=160), nullable=False),
        sa.Column("chain_name", sa.String(length=160), nullable=True),
        sa.Column("authorization_number", sa.String(length=80), nullable=True),
        sa.Column("remittance_guide", sa.String(length=100), nullable=True),
        sa.Column("total_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("administrative_status", sa.String(length=20), nullable=False),
        sa.Column("dispatch_status", sa.String(length=20), nullable=False),
        sa.Column("delivery_status", sa.String(length=30), nullable=False),
        sa.Column("incident_status", sa.String(length=30), nullable=False),
        sa.Column("return_status", sa.String(length=30), nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('purchase_order','sale_without_po','internal_consumption','sample','replacement','other')",
            name=op.f("ck_invoices_valid_source_type"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_invoices_created_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["purchase_order_id"],
            ["purchase_orders.id"],
            name=op.f("fk_invoices_purchase_order_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
    )
    op.create_index(
        op.f("ix_invoices_chain_name"), "invoices", ["chain_name"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_customer_name"), "invoices", ["customer_name"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_invoice_number"), "invoices", ["invoice_number"], unique=True
    )
    op.create_index(
        op.f("ix_invoices_purchase_order_id"),
        "invoices",
        ["purchase_order_id"],
        unique=False,
    )
    op.create_table(
        "invoice_alerts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("alert_type", sa.String(length=60), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("is_resolved", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_alerts_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_invoice_alerts_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_alerts")),
    )
    op.create_index(
        op.f("ix_invoice_alerts_invoice_id"),
        "invoice_alerts",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "invoice_lines",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.BigInteger(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("outside_purchase_order", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_invoice_lines_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_invoice_lines_invoice_id_invoices"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_invoice_lines_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoice_lines")),
        sa.UniqueConstraint("invoice_id", "product_id", name="uq_invoice_product"),
    )
    op.create_index(
        op.f("ix_invoice_lines_invoice_id"),
        "invoice_lines",
        ["invoice_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoice_lines_product_id"),
        "invoice_lines",
        ["product_id"],
        unique=False,
    )
    for table_name in ("invoices", "invoice_lines", "invoice_alerts"):
        op.execute(
            sa.text(f'ALTER TABLE public."{table_name}" ENABLE ROW LEVEL SECURITY')
        )
        op.execute(sa.text(f'REVOKE ALL ON TABLE public."{table_name}" FROM PUBLIC'))
        op.execute(
            sa.text(f"""DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='anon') THEN REVOKE ALL ON TABLE public."{table_name}" FROM anon; END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname='authenticated') THEN REVOKE ALL ON TABLE public."{table_name}" FROM authenticated; END IF;
        END $$""")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_invoice_lines_product_id"), table_name="invoice_lines")
    op.drop_index(op.f("ix_invoice_lines_invoice_id"), table_name="invoice_lines")
    op.drop_table("invoice_lines")
    op.drop_index(op.f("ix_invoice_alerts_invoice_id"), table_name="invoice_alerts")
    op.drop_table("invoice_alerts")
    op.drop_index(op.f("ix_invoices_purchase_order_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_number"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_customer_name"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_chain_name"), table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
