"""create stock adjustment workflow

Revision ID: f4b2ace7cb36
Revises: b4e9205ab100
Create Date: 2026-07-03 00:57:58.337505
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "f4b2ace7cb36"
down_revision: str | None = "b4e9205ab100"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stock_adjustment_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("decided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("previous_physical_confirmed", sa.BigInteger(), nullable=False),
        sa.Column("requested_physical_confirmed", sa.BigInteger(), nullable=False),
        sa.Column("position_version", sa.Integer(), nullable=False),
        sa.Column("request_reason", sa.Text(), nullable=False),
        sa.Column("decision_reason", sa.Text(), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending','approved','rejected','obsolete')",
            name=op.f("ck_stock_adjustment_requests_valid_status"),
        ),
        sa.CheckConstraint(
            "position_version > 0",
            name=op.f("ck_stock_adjustment_requests_position_version_positive"),
        ),
        sa.CheckConstraint(
            "previous_physical_confirmed >= 0",
            name=op.f("ck_stock_adjustment_requests_previous_physical_nonnegative"),
        ),
        sa.CheckConstraint(
            "requested_physical_confirmed >= 0",
            name=op.f("ck_stock_adjustment_requests_requested_physical_nonnegative"),
        ),
        sa.ForeignKeyConstraint(
            ["decided_by_user_id"],
            ["users.id"],
            name=op.f("fk_stock_adjustment_requests_decided_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_stock_adjustment_requests_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_stock_adjustment_requests_requested_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_adjustment_requests_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_adjustment_requests")),
    )
    op.create_index(
        op.f("ix_stock_adjustment_requests_decided_by_user_id"),
        "stock_adjustment_requests",
        ["decided_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_requests_product_id"),
        "stock_adjustment_requests",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_requests_requested_at"),
        "stock_adjustment_requests",
        ["requested_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_requests_requested_by_user_id"),
        "stock_adjustment_requests",
        ["requested_by_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_requests_status"),
        "stock_adjustment_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_adjustment_requests_warehouse_id"),
        "stock_adjustment_requests",
        ["warehouse_id"],
        unique=False,
    )
    op.execute(
        sa.text(
            'ALTER TABLE public."stock_adjustment_requests" ENABLE ROW LEVEL SECURITY'
        )
    )
    op.execute(
        sa.text('REVOKE ALL ON TABLE public."stock_adjustment_requests" FROM PUBLIC')
    )
    op.execute(
        sa.text("""
        DO $$ BEGIN
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
            REVOKE ALL ON TABLE public.stock_adjustment_requests FROM anon;
          END IF;
          IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
            REVOKE ALL ON TABLE public.stock_adjustment_requests FROM authenticated;
          END IF;
        END $$
    """)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_stock_adjustment_requests_warehouse_id"),
        table_name="stock_adjustment_requests",
    )
    op.drop_index(
        op.f("ix_stock_adjustment_requests_status"),
        table_name="stock_adjustment_requests",
    )
    op.drop_index(
        op.f("ix_stock_adjustment_requests_requested_by_user_id"),
        table_name="stock_adjustment_requests",
    )
    op.drop_index(
        op.f("ix_stock_adjustment_requests_requested_at"),
        table_name="stock_adjustment_requests",
    )
    op.drop_index(
        op.f("ix_stock_adjustment_requests_product_id"),
        table_name="stock_adjustment_requests",
    )
    op.drop_index(
        op.f("ix_stock_adjustment_requests_decided_by_user_id"),
        table_name="stock_adjustment_requests",
    )
    op.drop_table("stock_adjustment_requests")
    # ### end Alembic commands ###
